-- ============================================================
--  Boldr CS Intelligence — Supabase Schema
--  Run this entire file in the Supabase SQL Editor once.
--  Dashboard: https://supabase.com → your project → SQL Editor
-- ============================================================


-- ── 1. Tickets Inbox ─────────────────────────────────────────
--  Incoming customer tickets submitted via the dashboard or CSV.
--  WF1 polls this table for unprocessed tickets.

create table if not exists tickets_inbox (
  id                bigserial primary key,
  ticket_id         text        unique not null,
  subject           text,
  customer_name     text,
  customer_email    text,
  customer_question text,
  channel           text        default 'web',
  date_received     timestamptz default now(),
  processed         boolean     default false
);


-- ── 2. Knowledge Sources ─────────────────────────────────────
--  Raw KB source documents (FAQ, product reference, rate cards).
--  WF1 builds its knowledge base from these at runtime.
--  Seed with 4 rows: faq, product_reference, engraving_rates, servicing_rates.

create table if not exists knowledge_sources (
  id          bigserial primary key,
  name        text        unique not null,  -- 'faq' | 'product_reference' | 'engraving_rates' | 'servicing_rates'
  content     text        not null,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);


-- ── 3. Knowledge Base ────────────────────────────────────────
--  Individual Q&A pairs. WF2 writes approved KB additions here.

create table if not exists knowledge_base (
  id          bigserial primary key,
  question    text        not null,
  answer      text        not null,
  theme       text,
  source      text,
  created_at  timestamptz default now()
);


-- ── 2. Processed Tickets ──────────────────────────────────────
--  One row per ticket processed by WF1.

create table if not exists tickets_processed (
  id               bigserial primary key,
  ticket_id        text        unique not null,
  subject          text,
  customer_name    text,
  customer_email   text,
  customer_question text,
  channel          text,
  buyer_persona    text,
  theme            text,
  outcome          text,        -- 'DRAFT_READY' | 'KNOWLEDGE_GAP'
  draft_reply      text,
  confidence       numeric,
  kb_source        text,
  date_received    timestamptz,
  processed_at     timestamptz default now()
);


-- ── 3. Knowledge Gaps ─────────────────────────────────────────
--  Logged when WF1 cannot find a KB match.
--  Resolved via the dashboard → WF2.

create table if not exists knowledge_gaps (
  id               bigserial primary key,
  ticket_id        text        not null,
  subject          text,
  customer_name    text,
  customer_email   text,
  customer_question text,
  channel          text,
  buyer_persona    text,
  theme            text,
  gap_reason       text,
  status           text        default 'open',  -- 'open' | 'resolved'
  date_received    timestamptz,
  processed_at     timestamptz default now()
);


-- ── 4. KB Additions ───────────────────────────────────────────
--  Candidate KB entries generated by WF2 after a gap is resolved.
--  Approved entries are added to knowledge_base by WF2.

create table if not exists kb_additions (
  id           bigserial primary key,
  ticket_id    text,
  question     text,
  answer       text,
  theme        text,
  status       text        default 'pending',  -- 'pending' | 'approved' | 'rejected'
  approved_at  timestamptz,
  created_at   timestamptz default now()
);


-- ── 5. Marketing Briefs ───────────────────────────────────────
--  Generated by WF3 every 6 hours when 5+ open gaps exist.

create table if not exists marketing_briefs (
  id                       bigserial primary key,
  ticket_count             int,
  gap_count                int,
  executive_summary        text,
  top_themes               jsonb,
  top_personas             jsonb,
  recurring_gaps           jsonb,
  marketing_opportunities  jsonb,
  content_recommendations  jsonb,
  product_feedback         text,
  generated_at             timestamptz default now()
);


-- ── 6. Marketing Insights ─────────────────────────────────────
--  One AI-scored insight generated per knowledge gap (WF3).

create table if not exists marketing_insights (
  id               bigserial primary key,
  ticket_id        text,
  theme            text,
  buyer_persona    text,
  channel          text,
  customer_question text,
  marketing_angle  text,
  campaign_idea    text,
  test_suggestion  text,
  score_uniqueness numeric,
  score_conversion numeric,
  score_overall    numeric,
  rationale        text,
  created_at       timestamptz default now()
);


-- ── 7. Gap Sentiment ──────────────────────────────────────────
--  Deduplicated sentiment labels extracted inline by WF1.
--  Each label is searched across Reddit, WatchUSeek, and Amazon.
--  Upserting on `label` merges data from repeat runs.

create table if not exists gap_sentiment (
  id                 bigserial primary key,
  label              text        unique not null,
  classification     text,        -- 'Market Signal' | 'Boldr Specific'
  gap_count          int          default 1,
  original_questions jsonb,
  reddit_url         text,
  reddit_name        text,
  reddit_score       numeric,
  watchuseek_url     text,
  watchuseek_name    text,
  watchuseek_score   numeric,
  amazon_url         text,
  amazon_name        text,
  amazon_score       numeric,
  overall_score      numeric,
  summary            text,
  created_at         timestamptz  default now(),
  updated_at         timestamptz  default now()
);


-- ── Row Level Security ────────────────────────────────────────
--  Workflows use the service role key (bypasses RLS).
--  Enable RLS on all tables for production hardening.

alter table tickets_inbox        enable row level security;
alter table knowledge_sources    enable row level security;
alter table knowledge_base       enable row level security;
alter table tickets_processed    enable row level security;
alter table knowledge_gaps       enable row level security;
alter table kb_additions         enable row level security;
alter table marketing_briefs     enable row level security;
alter table marketing_insights   enable row level security;
alter table gap_sentiment        enable row level security;


-- ── Reset helper (use during testing only) ────────────────────
--
--  truncate table tickets_processed   restart identity cascade;
--  truncate table knowledge_gaps      restart identity cascade;
--  truncate table kb_additions        restart identity cascade;
--  truncate table marketing_briefs    restart identity cascade;
--  truncate table marketing_insights  restart identity cascade;
--  truncate table gap_sentiment       restart identity cascade;
--
--  -- Reset ticket processing flag so WF1 picks them up again
--  update tickets_inbox set processed = false;
--
--  -- knowledge_sources and tickets_inbox data is preserved by default.
